image: bitwalker/alpine-elixir-phoenix:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - git remote add gigalixir https://dasky%40hey.com:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_URL.git
    - git push -f gigalixir HEAD:refs/heads/master
  only:
    - main
